#!/bin/bash
# Program:
#   Differential expression (RNA) for chicken data with safe preprocessing
#   and enhanced, configurable visualizations.
#
# Usage:
#   ./differential.sh RNA
#
#SBATCH --job-name=differential_chicken
#SBATCH --output=./log/DGE/%x.log
#SBATCH -n 8
#SBATCH --mem=64GB

set -euo pipefail

# ---------------- Args / Mode ----------------
if [[ -z "${1:-}" ]]; then
  echo "Error: Analysis mode not specified." >&2
  echo "Usage: $0 RNA" >&2
  exit 1
fi

ANALYSIS_MODE="$1"
# (Logic unchanged)
case "$ANALYSIS_MODE" in
  RNA) OUTPUT_PREFIX="RNA_DGE_analysis" ;;
  *)   echo "Error: Invalid mode '$ANALYSIS_MODE' (use RNA)." >&2; exit 1 ;;
esac

# ---------------- Paths & Parameters ----------------
read_count="/home/johan/johan/output/chicken/combined.HTseq_report"
metadata_in="/home/johan/johan/output/chicken/metadata.csv"
r_script_path="./differential.R"

# --- Output ---
output_dir="/home/johan/johan/output/chicken/${OUTPUT_PREFIX}"
mkdir -p "$output_dir" ./log/DGE

# --- Contrast & Design ---
# Compare high_egg vs low_egg, adjusting for tissue (uterus/ovary)
CONTRAST_FACTOR="egg_production"
NUMERATOR="high_egg"
DENOMINATOR="low_egg"
BATCH_COLUMN="tissue"   # design ~ tissue + egg_production

# --- [NEW] Visualization Control ---
# These variables control the aesthetics of the plots generated by differential.R
PCA_COLOR_BY="egg_production" # Metadata column for PCA point color
PCA_SHAPE_BY="tissue"       # Metadata column for PCA point shape
PCA_LABEL_BY="sample"       # Metadata column for PCA point labels
PCA_ADD_ELLIPSE=true        # Add grouping ellipses to PCA? (true/false)
TOP_N_HEATMAP=50            # Number of top genes for the heatmap
TOP_N_VOLCANO_LABELS=15     # Number of top genes to label on the volcano plot
TRANSPARENT_PNG=true        # Use transparent background for PNGs?

echo "====================================================================="
date
echo "Starting differential analysis."
echo "Mode: $ANALYSIS_MODE"
echo "Output: $output_dir"
echo

# ---------------- Sanity Checks ----------------
# (Logic unchanged)
[[ -f "$read_count" ]]   || { echo "Counts not found: $read_count" >&2; exit 1; }
[[ -f "$metadata_in" ]]  || { echo "Metadata not found: $metadata_in" >&2; exit 1; }
[[ -f "$r_script_path" ]] || { echo "R script not found: $r_script_path" >&2; exit 1; }


# ---------------- 1) Preprocessing: Normalize metadata & subset data ----------------
# The inline python scripts are efficient and remain unchanged.
META_NORM="${output_dir}/metadata.norm.csv"
# (Python script for metadata normalization is unchanged)
python3 - "$metadata_in" "$META_NORM" <<'PY'
import re, sys, pandas as pd
src, dst = sys.argv[1], sys.argv[2]
m = pd.read_csv(src)
def modern(df):
    need = ['sample','subject','tissue','replicate','egg_production','assay_type']
    if all(c in df.columns for c in need):
        out = df[need].copy(); out['assay_type'] = out['assay_type'].astype(str).str.upper(); return out
    return None
def legacy(df):
    if 'SampleID' not in df.columns: return None
    rows = []
    for sid in df['SampleID'].astype(str):
        mo = re.match(r'^(RH)(\d+)_(ovary|uterus)_rep(\d+)$', sid, flags=re.I)
        if mo:
            rh, num, tissue, rep = mo.group(1).upper(), int(mo.group(2)), mo.group(3).lower(), int(mo.group(4))
            egg = 'high_egg' if 1 <= num <= 5 else 'low_egg'
            rows.append(dict(sample=sid, subject=f"{rh}{num}", tissue=tissue, replicate=rep, egg_production=egg, assay_type='RNA'))
        else:
            rows.append(dict(sample=sid, subject='NA', tissue='NA', replicate='NA', egg_production='low_egg', assay_type='RNA'))
    return pd.DataFrame(rows, columns=['sample','subject','tissue','replicate','egg_production','assay_type'])
out = modern(m)
if out is None: out = legacy(m)
if out is None: raise SystemExit("Unrecognized metadata format.")
out.to_csv(dst, index=False)
print(f"Wrote normalized metadata: {dst} (n={len(out)})")
PY

META_RNA="${output_dir}/metadata.RNA.csv"
# (Python script for RNA filtering is unchanged)
python3 - "$META_NORM" "$META_RNA" <<'PY'
import sys, pandas as pd
src, dst = sys.argv[1], sys.argv[2]
m = pd.read_csv(src); m = m[m['assay_type'].astype(str).str.upper()=='RNA'].copy()
if m.empty: raise SystemExit("No RNA rows after filtering.")
m.to_csv(dst, index=False)
print(f"Wrote RNA-only metadata: {dst} (n={len(m)})")
PY

COUNT_USED="${output_dir}/counts.used.tsv"
META_USED="${output_dir}/metadata.used.csv"
# (Python script for subsetting/syncing is unchanged)
python3 - "$read_count" "$META_RNA" "$COUNT_USED" "$META_USED" <<'PY'
import sys, pandas as pd
cnt_fp, meta_fp, out_cnt, out_meta = sys.argv[1:]
cnt  = pd.read_csv(cnt_fp, sep="\t"); meta = pd.read_csv(meta_fp)
if "GeneID" not in cnt.columns: cnt = cnt.rename(columns={cnt.columns[0]: "GeneID"})
sample_set = set(meta["sample"].astype(str))
cols = ["GeneID"] + [c for c in cnt.columns if c != "GeneID" and c in sample_set]
sub = cnt.loc[:, cols].copy()
if sub.shape[1] <= 1: raise SystemExit("No matching sample columns between counts and metadata.")
meta2 = meta[meta["sample"].isin([c for c in sub.columns if c != "GeneID"])].copy()
meta2 = meta2.set_index("sample").loc[[c for c in sub.columns if c != "GeneID"]].reset_index()
sub.to_csv(out_cnt, sep="\t", index=False); meta2.to_csv(out_meta, index=False)
print(f"Wrote counts: {out_cnt} (genes={len(sub)} cols={sub.shape[1]})")
print(f"Wrote meta  : {out_meta} (n={len(meta2)})")
PY

read_count_used="$COUNT_USED"
metadata_used="$META_USED"

# ---------------- 2) Run R for DGE Analysis ----------------
echo
echo "#######################################"
echo "# Running differential.R              #"
echo "#######################################"
echo "Design: ~ ${BATCH_COLUMN} + ${CONTRAST_FACTOR}"
echo "Contrast: ${CONTRAST_FACTOR} (${NUMERATOR} vs ${DENOMINATOR})"
echo

# --- [IMPROVED] Build the command with new visualization arguments ---
CMD=( Rscript "$r_script_path"
  --counts "$read_count_used"
  --metadata "$metadata_used"
  --outdir "$output_dir"
  --sampleColumn "sample"
  --contrastFactor "$CONTRAST_FACTOR"
  --contrastNumerator "$NUMERATOR"
  --contrastDenominator "$DENOMINATOR"
  --batchColumn "$BATCH_COLUMN"
  --cores 8
  --padj 0.05
  --lfc 1
  --outputFormats "png,pdf"
  # Add visualization arguments
  --pcaColor "$PCA_COLOR_BY"
  --pcaShape "$PCA_SHAPE_BY"
  --pcaLabel "$PCA_LABEL_BY"
  --topNHeatmap "$TOP_N_HEATMAP"
  --topNLabels "$TOP_N_VOLCANO_LABELS"
)

# Add flag-style arguments
if [[ "$TRANSPARENT_PNG" == "true" ]]; then
  CMD+=( --transparentPNG )
fi
if [[ "$PCA_ADD_ELLIPSE" == "true" ]]; then
  CMD+=( --pcaEllipse )
fi

echo "Executing:"
printf ' %q' "${CMD[@]}"; echo
echo "---------------------------------------"

# Execute the command
"${CMD[@]}"

echo
echo "#############################"
echo "# Analysis complete         #"
echo "#############################"
echo "Results are in: $output_dir"
date
echo "====================================================================="